---
abstract: 'Command line processing with extensive usage generation'
author:
  - 'Oliver Schieche <schiecheo@cpan.org>'
build_requires:
  Module::Build: '0.30'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  Module::Build: '0.30'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142690'
license: restrictive
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: libgetopt-complete-perl
provides:
  Getopt::Complete:
    file: lib/Getopt/Complete.pm
    version: v0.2.1
  Getopt::Complete::Rule:
    file: lib/Getopt/Complete.pm
version: v0.2.1
